import {
  Organization,
  ServiceCategory,
  UserProfile,
  Ticket,
  Asset,
  SLARule,
  PreventiveMaintenanceSchedule,
  AuditLogItem,
  AppNotification,
} from './types';

export const GLOBAL_SUPER_ADMIN_ORG: Organization = {
  id: 'global-facilityos-all',
  name: 'FacilityOS Global Platform',
  code: 'FOS-GLOBAL-2026',
  type: 'other',
  location: 'Global Operations Headquarters',
  logo: '🌐',
  primaryColor: '#4f46e5',
  secondaryColor: '#6366f1',
  welcomeMessage: 'FacilityOS System Super Admin Control Hub. Monitoring across all platform tenants.',
  contactEmail: 'superadmin@facilityos.io',
  contactPhone: '+1 800 FACOS SYS',
  verified: true,
  totalServicesCount: 14,
  enabledServiceIds: [
    'plumbing',
    'electrical',
    'carpentry',
    'cleaning',
    'ac_hvac',
    'civil',
    'furniture',
    'wifi_network',
    'it_support',
    'hostel_maint',
    'transport',
    'security_maint',
    'water_supply',
    'lift_elevator',
  ],
};

export const DEMO_ORGANIZATIONS: Organization[] = [
  // UNIVERSITIES & COLLEGES
  {
    id: 'woxsen-university',
    name: 'Woxsen University',
    code: 'WOXSEN-2026',
    type: 'university',
    location: 'Hyderabad, Telangana',
    logo: '🎓',
    primaryColor: '#1e3a8a',
    secondaryColor: '#3b82f6',
    welcomeMessage: 'Welcome to Woxsen Campus Ops Portal. Report and track facility requests 24/7.',
    contactEmail: 'facility@woxsen.edu.in',
    contactPhone: '+91 40 2345 6789',
    verified: true,
    totalServicesCount: 12,
    enabledServiceIds: [
      'plumbing',
      'electrical',
      'carpentry',
      'cleaning',
      'ac_hvac',
      'civil',
      'furniture',
      'wifi_network',
      'it_support',
      'hostel_maint',
      'transport',
      'security_maint',
    ],
  },
  {
    id: 'iit-bombay',
    name: 'IIT Bombay Campus',
    code: 'IITB-2026',
    type: 'university',
    location: 'Powai, Mumbai',
    logo: '🏛️',
    primaryColor: '#0f172a',
    secondaryColor: '#2563eb',
    welcomeMessage: 'IIT Bombay Estate & Maintenance Portal for Departmental Labs & Hostels.',
    contactEmail: 'estate@iitb.ac.in',
    contactPhone: '+91 22 2576 7000',
    verified: true,
    totalServicesCount: 10,
    enabledServiceIds: [
      'electrical',
      'plumbing',
      'wifi_network',
      'it_support',
      'ac_hvac',
      'civil',
      'hostel_maint',
      'cleaning',
      'transport',
      'security_maint',
    ],
  },
  {
    id: 'manipal-university',
    name: 'Manipal Academy of Higher Education',
    code: 'MAHE-2026',
    type: 'university',
    location: 'Manipal, Karnataka',
    logo: '🏫',
    primaryColor: '#854d0e',
    secondaryColor: '#eab308',
    welcomeMessage: 'MAHE Campus Operations & Student Services Support Console.',
    contactEmail: 'facilities@manipal.edu',
    contactPhone: '+91 820 292 2400',
    verified: true,
    totalServicesCount: 11,
    enabledServiceIds: [
      'plumbing',
      'electrical',
      'hostel_maint',
      'wifi_network',
      'cleaning',
      'ac_hvac',
      'furniture',
      'civil',
      'transport',
      'security_maint',
      'it_support',
    ],
  },
  {
    id: 'bits-pilani',
    name: 'BITS Pilani Campus',
    code: 'BITS-2026',
    type: 'university',
    location: 'Pilani, Rajasthan',
    logo: '🔬',
    primaryColor: '#1e1b4b',
    secondaryColor: '#6366f1',
    welcomeMessage: 'BITS Pilani Campus Maintenance & Hostel Service Portal.',
    contactEmail: 'gad@pilani.bits-pilani.ac.in',
    contactPhone: '+91 1596 245 073',
    verified: true,
    totalServicesCount: 10,
    enabledServiceIds: [
      'electrical',
      'plumbing',
      'wifi_network',
      'it_support',
      'ac_hvac',
      'civil',
      'furniture',
      'hostel_maint',
      'cleaning',
      'security_maint',
    ],
  },
  {
    id: 'srm-ist',
    name: 'SRM Institute of Science & Tech',
    code: 'SRM-2026',
    type: 'university',
    location: 'Kattankulathur, Chennai',
    logo: '🎓',
    primaryColor: '#15803d',
    secondaryColor: '#22c55e',
    welcomeMessage: 'SRMIST Facility & Hostel Maintenance Helpdesk.',
    contactEmail: 'maintenance@srmist.edu.in',
    contactPhone: '+91 44 2745 5510',
    verified: true,
    totalServicesCount: 9,
    enabledServiceIds: [
      'plumbing',
      'electrical',
      'cleaning',
      'wifi_network',
      'hostel_maint',
      'ac_hvac',
      'civil',
      'transport',
      'security_maint',
    ],
  },

  // APARTMENTS & GATED COMMUNITIES
  {
    id: 'green-valley',
    name: 'Green Valley Residency',
    code: 'GREEN-2026',
    type: 'apartment',
    location: 'Bengaluru, Karnataka',
    logo: '🏡',
    primaryColor: '#065f46',
    secondaryColor: '#10b981',
    welcomeMessage: 'Green Valley Resident Care & Maintenance Hub. Premium service for residents.',
    contactEmail: 'care@greenvalley.org',
    contactPhone: '+91 80 8765 4321',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'plumbing',
      'electrical',
      'cleaning',
      'security_maint',
      'water_supply',
      'lift_elevator',
      'ac_hvac',
      'carpentry',
    ],
  },
  {
    id: 'prestige-falcon',
    name: 'Prestige Falcon City',
    code: 'FALCON-2026',
    type: 'apartment',
    location: 'Kanakapura Road, Bengaluru',
    logo: '🏙️',
    primaryColor: '#1e293b',
    secondaryColor: '#38bdf8',
    welcomeMessage: 'Prestige Falcon City Association & Facility Maintenance Portal.',
    contactEmail: 'helpdesk@prestigefalcon.in',
    contactPhone: '+91 80 4000 5000',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'lift_elevator',
      'water_supply',
      'plumbing',
      'electrical',
      'cleaning',
      'security_maint',
      'ac_hvac',
      'civil',
    ],
  },
  {
    id: 'dlf-crest',
    name: 'DLF The Crest Phase 5',
    code: 'DLF-2026',
    type: 'apartment',
    location: 'Golf Course Road, Gurugram',
    logo: '🏰',
    primaryColor: '#701a75',
    secondaryColor: '#d946ef',
    welcomeMessage: 'DLF Crest Ultra Luxury Condominium Resident Services.',
    contactEmail: 'concierge@dlfcrest.com',
    contactPhone: '+91 124 490 0000',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'ac_hvac',
      'lift_elevator',
      'water_supply',
      'plumbing',
      'electrical',
      'cleaning',
      'security_maint',
      'carpentry',
    ],
  },
  {
    id: 'hiranandani-powai',
    name: 'Hiranandani Gardens',
    code: 'HIRAN-2026',
    type: 'apartment',
    location: 'Powai, Mumbai',
    logo: '🏬',
    primaryColor: '#831843',
    secondaryColor: '#ec4899',
    welcomeMessage: 'Hiranandani Gardens Resident Estate & Maintenance Portal.',
    contactEmail: 'care@hiranandanipowai.com',
    contactPhone: '+91 22 2571 5000',
    verified: true,
    totalServicesCount: 7,
    enabledServiceIds: [
      'water_supply',
      'lift_elevator',
      'plumbing',
      'electrical',
      'cleaning',
      'security_maint',
      'civil',
    ],
  },

  // OFFICE & CORPORATE CAMPUSES
  {
    id: 'invartech-solutions',
    name: 'InvarTech Solutions HQ',
    code: 'INVAR-2026',
    type: 'office',
    location: 'Cyber City, Gurugram',
    logo: '🏢',
    primaryColor: '#4c1d95',
    secondaryColor: '#8b5cf6',
    welcomeMessage: 'Workplace Operations & Maintenance Console for InvarTech Employees.',
    contactEmail: 'facilities@invartech.com',
    contactPhone: '+91 124 555 0199',
    verified: true,
    totalServicesCount: 7,
    enabledServiceIds: [
      'it_support',
      'electrical',
      'ac_hvac',
      'furniture',
      'cleaning',
      'wifi_network',
      'security_maint',
    ],
  },
  {
    id: 'microsoft-idc',
    name: 'Microsoft India Dev Center',
    code: 'MSFT-2026',
    type: 'office',
    location: 'Gachibowli, Hyderabad',
    logo: '💼',
    primaryColor: '#0284c7',
    secondaryColor: '#38bdf8',
    welcomeMessage: 'Microsoft IDC Facilities & Real Estate Operations Portal.',
    contactEmail: 'idchelp@microsoft.com',
    contactPhone: '+91 40 6699 0000',
    verified: true,
    totalServicesCount: 7,
    enabledServiceIds: [
      'it_support',
      'wifi_network',
      'ac_hvac',
      'electrical',
      'furniture',
      'cleaning',
      'security_maint',
    ],
  },
  {
    id: 'infosys-ecity',
    name: 'Infosys World Headquarters',
    code: 'INFY-2026',
    type: 'office',
    location: 'Electronic City, Bengaluru',
    logo: '🌐',
    primaryColor: '#0369a1',
    secondaryColor: '#0ea5e9',
    welcomeMessage: 'Infosys Campus Infrastructure & IT Operations Desk.',
    contactEmail: 'facilities_ecity@infosys.com',
    contactPhone: '+91 80 2852 0261',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'it_support',
      'electrical',
      'ac_hvac',
      'wifi_network',
      'cleaning',
      'furniture',
      'transport',
      'security_maint',
    ],
  },

  // HOSPITALS & MEDICAL CENTERS
  {
    id: 'apollo-main',
    name: 'Apollo Hospitals Main Hub',
    code: 'APOLLO-2026',
    type: 'hospital',
    location: 'Greams Road, Chennai',
    logo: '🏥',
    primaryColor: '#991b1b',
    secondaryColor: '#ef4444',
    welcomeMessage: 'Apollo Hospitals Biomedical & Critical Facility Maintenance Console.',
    contactEmail: 'bio_maint@apollohospitals.com',
    contactPhone: '+91 44 2829 0200',
    verified: true,
    totalServicesCount: 9,
    enabledServiceIds: [
      'electrical',
      'ac_hvac',
      'water_supply',
      'lift_elevator',
      'cleaning',
      'plumbing',
      'security_maint',
      'it_support',
      'civil',
    ],
  },
  {
    id: 'fortis-fmri',
    name: 'Fortis Memorial Research Institute',
    code: 'FORTIS-2026',
    type: 'hospital',
    location: 'Sector 44, Gurugram',
    logo: '🩺',
    primaryColor: '#166534',
    secondaryColor: '#22c55e',
    welcomeMessage: 'Fortis FMRI Critical Infrastructure & Clinical Facility Operations.',
    contactEmail: 'facility.fmri@fortishealthcare.com',
    contactPhone: '+91 124 492 1000',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'ac_hvac',
      'electrical',
      'lift_elevator',
      'water_supply',
      'cleaning',
      'plumbing',
      'security_maint',
      'it_support',
    ],
  },
  {
    id: 'manipal-hospital',
    name: 'Manipal Super Speciality Hospital',
    code: 'MH-2026',
    type: 'hospital',
    location: 'Whitefield, Bengaluru',
    logo: '🏥',
    primaryColor: '#0e7490',
    secondaryColor: '#06b6d4',
    welcomeMessage: 'Manipal Hospital Facilities & Oxygen Supply Engineering Console.',
    contactEmail: 'info@manipalhospitals.com',
    contactPhone: '+91 80 2502 4444',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'electrical',
      'water_supply',
      'ac_hvac',
      'lift_elevator',
      'cleaning',
      'plumbing',
      'security_maint',
      'civil',
    ],
  },

  // HOSTELS & STUDENT HOUSING
  {
    id: 'xavier-hostel',
    name: "St. Xavier's Student Residence",
    code: 'XAVIER-2026',
    type: 'hostel',
    location: 'Fort, Mumbai',
    logo: '🛌',
    primaryColor: '#312e81',
    secondaryColor: '#6366f1',
    welcomeMessage: "St. Xavier's Student Hostel Care & Repair Portal.",
    contactEmail: 'hostel@xaviers.edu',
    contactPhone: '+91 22 2262 0661',
    verified: true,
    totalServicesCount: 7,
    enabledServiceIds: [
      'hostel_maint',
      'plumbing',
      'electrical',
      'wifi_network',
      'cleaning',
      'furniture',
      'carpentry',
    ],
  },
  {
    id: 'scholars-nest',
    name: "Scholar's Nest Executive Hostel",
    code: 'NEST-2026',
    type: 'hostel',
    location: 'Viman Nagar, Pune',
    logo: '🛏️',
    primaryColor: '#854d0e',
    secondaryColor: '#f59e0b',
    welcomeMessage: "Scholar's Nest Premium Student Housing Support Desk.",
    contactEmail: 'care@scholarsnest.in',
    contactPhone: '+91 20 6720 1100',
    verified: true,
    totalServicesCount: 7,
    enabledServiceIds: [
      'hostel_maint',
      'wifi_network',
      'plumbing',
      'electrical',
      'ac_hvac',
      'cleaning',
      'furniture',
    ],
  },

  // SCHOOLS
  {
    id: 'doon-school',
    name: 'The Doon School Campus',
    code: 'DOON-2026',
    type: 'school',
    location: 'Dehradun, Uttarakhand',
    logo: '🏫',
    primaryColor: '#1e3a8a',
    secondaryColor: '#3b82f6',
    welcomeMessage: 'The Doon School Campus & Estate Management Helpdesk.',
    contactEmail: 'estate@doonschool.com',
    contactPhone: '+91 135 252 6400',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'electrical',
      'plumbing',
      'carpentry',
      'cleaning',
      'civil',
      'furniture',
      'transport',
      'security_maint',
    ],
  },
  {
    id: 'dps-intl',
    name: 'DPS International Campus',
    code: 'DPS-2026',
    type: 'school',
    location: 'RK Puram, New Delhi',
    logo: '🎒',
    primaryColor: '#166534',
    secondaryColor: '#22c55e',
    welcomeMessage: 'DPS International Facility Maintenance Console.',
    contactEmail: 'facilities@dpsrkp.net',
    contactPhone: '+91 11 2617 4200',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'electrical',
      'ac_hvac',
      'it_support',
      'plumbing',
      'cleaning',
      'furniture',
      'transport',
      'security_maint',
    ],
  },

  // RESIDENTIAL COMMUNITIES
  {
    id: 'palm-meadows',
    name: 'Palm Meadows Villa Society',
    code: 'PALM-2026',
    type: 'residential',
    location: 'Whitefield, Bengaluru',
    logo: '🌴',
    primaryColor: '#047857',
    secondaryColor: '#10b981',
    welcomeMessage: 'Palm Meadows Villa Association Maintenance & Security Desk.',
    contactEmail: 'office@palmmeadows.org',
    contactPhone: '+91 80 2845 2200',
    verified: true,
    totalServicesCount: 7,
    enabledServiceIds: [
      'water_supply',
      'electrical',
      'plumbing',
      'cleaning',
      'security_maint',
      'civil',
      'ac_hvac',
    ],
  },

  // COMMERCIAL BUILDINGS
  {
    id: 'phoenix-marketcity',
    name: 'Phoenix Marketcity Commercial Hub',
    code: 'PHOENIX-2026',
    type: 'commercial',
    location: 'Kurla, Mumbai',
    logo: '🏬',
    primaryColor: '#be123c',
    secondaryColor: '#f43f5e',
    welcomeMessage: 'Phoenix Commercial Center Maintenance & Escalator Operations.',
    contactEmail: 'ops@phoenixmarketcity.com',
    contactPhone: '+91 22 6180 1100',
    verified: true,
    totalServicesCount: 8,
    enabledServiceIds: [
      'ac_hvac',
      'lift_elevator',
      'electrical',
      'plumbing',
      'cleaning',
      'security_maint',
      'civil',
      'it_support',
    ],
  },
];

export const ALL_SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'plumbing',
    name: 'Plumbing',
    iconName: 'Droplets',
    description: 'Tap leakages, pipe blockages, flush issues, water heaters',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'electrical',
    name: 'Electrical',
    iconName: 'Zap',
    description: 'Lights, switches, power sockets, ceiling fans, MCB trips',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    iconName: 'Hammer',
    description: 'Doors, windows, locks, study tables, wardrobes, cupboards',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 48,
  },
  {
    id: 'cleaning',
    name: 'Cleaning & Housekeeping',
    iconName: 'Droplets',
    description: 'Deep room cleaning, garbage clearance, sanitization',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'ac_hvac',
    name: 'AC & HVAC',
    iconName: 'Wind',
    description: 'AC cooling issues, noise, water leakage from indoor unit, remote control',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'civil',
    name: 'Civil Maintenance',
    iconName: 'Building',
    description: 'Wall dampness, paint peeling, tile damage, roof leakage',
    defaultPriority: 'low',
    enabled: true,
    estimatedHours: 72,
  },
  {
    id: 'furniture',
    name: 'Furniture & Fixtures',
    iconName: 'Armchair',
    description: 'Chair repair, desk adjustments, bed frame, curtains',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 48,
  },
  {
    id: 'wifi_network',
    name: 'Wi-Fi & Network',
    iconName: 'Wifi',
    description: 'LAN port repair, slow internet, router issue, AP offline',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 8,
  },
  {
    id: 'it_support',
    name: 'IT Support & AV',
    iconName: 'Monitor',
    description: 'Projector issues, desktop setup, printer repair, smart board',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'hostel_maint',
    name: 'Hostel Maintenance',
    iconName: 'Bed',
    description: 'Mess equipment, common room TV, laundry machine issue',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'transport',
    name: 'Transport & Shuttle',
    iconName: 'Bus',
    description: 'Bus schedule query, EV charger port repair, parking slot',
    defaultPriority: 'low',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'security_maint',
    name: 'Security & Access Control',
    iconName: 'ShieldAlert',
    description: 'Biometric scanner, RFID card key, CCTV camera, gate barrier',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 6,
  },
  {
    id: 'water_supply',
    name: 'Water Supply',
    iconName: 'Waves',
    description: 'Water pressure, main inlet valve, tank overflow',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'lift_elevator',
    name: 'Lift & Elevator',
    iconName: 'ArrowUpDown',
    description: 'Lift breakdown, door sensor, emergency button check',
    defaultPriority: 'critical',
    enabled: true,
    estimatedHours: 4,
  },
];

export const DEMO_USERS: UserProfile[] = [
  // Woxsen University Users
  {
    id: 'user-student-1',
    orgId: 'woxsen-university',
    name: 'Aarav Sharma',
    email: 'student@university.edu',
    phone: '+91 98765 43210',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Computer Science (B.Tech 3rd Yr)',
    roomOrUnit: 'Hostel A - Room 204',
    accessTokenNo: 'WOX-8849-T',
    accessPin: '2026',
  },
  {
    id: 'worker-ravi',
    orgId: 'woxsen-university',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@woxsen.edu.in',
    phone: '+91 98220 11223',
    role: 'worker',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    skills: ['Plumbing', 'Water Supply', 'Sanitary Fittings'],
    rating: 4.8,
    totalJobsCompleted: 142,
    currentWorkload: 1,
    isAvailable: true,
    accessTokenNo: 'WRK-5050-T',
    accessPin: '5050',
  },
  {
    id: 'worker-suresh',
    orgId: 'woxsen-university',
    name: 'Suresh Patel',
    email: 'suresh.patel@woxsen.edu.in',
    phone: '+91 98330 33445',
    role: 'worker',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    skills: ['Electrical', 'AC & HVAC', 'Fan Repair'],
    rating: 4.9,
    totalJobsCompleted: 198,
    currentWorkload: 2,
    isAvailable: true,
    accessTokenNo: 'WRK-6060-T',
    accessPin: '6060',
  },
  {
    id: 'manager-warden',
    orgId: 'woxsen-university',
    name: 'Dr. Rajesh Verma',
    email: 'warden.hostela@woxsen.edu.in',
    phone: '+91 94450 99887',
    role: 'warden',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    department: 'Hostel Operations',
    accessTokenNo: 'WDN-3030-T',
    accessPin: '3030',
  },
  {
    id: 'admin-1',
    orgId: 'woxsen-university',
    name: 'Ananya Reddy',
    email: 'admin@facilityos.io',
    phone: '+91 90000 12345',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Chief Facility Officer',
    accessTokenNo: 'ADM-1010-T',
    accessPin: '1010',
  },

  // Green Valley Residency Users
  {
    id: 'user-resident-1',
    orgId: 'green-valley',
    name: 'Priya Nambiar',
    email: 'resident@greenvalley.com',
    phone: '+91 98111 22334',
    role: 'resident',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    department: 'Tower 3 Resident',
    roomOrUnit: 'Tower 3 - Flat 1204',
    accessTokenNo: 'GV-4412-T',
    accessPin: '1234',
  },
  {
    id: 'worker-karthik',
    orgId: 'green-valley',
    name: 'Karthik Nair',
    email: 'karthik@greenvalley.org',
    phone: '+91 98770 99881',
    role: 'worker',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    skills: ['Lift & Elevator', 'Plumbing', 'Water Supply'],
    rating: 4.9,
    totalJobsCompleted: 110,
    currentWorkload: 1,
    isAvailable: true,
    accessTokenNo: 'GV-WRK-10',
    accessPin: '1010',
  },
  {
    id: 'manager-green',
    orgId: 'green-valley',
    name: 'Meera Krishnan',
    email: 'manager@greenvalley.org',
    phone: '+91 98440 11223',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    department: 'Community Management',
    accessTokenNo: 'GV-MGR-20',
    accessPin: '2020',
  },

  // InvarTech Solutions HQ Users
  {
    id: 'user-employee-1',
    orgId: 'invartech-solutions',
    name: 'Vikram Mehta',
    email: 'employee@company.com',
    phone: '+91 99887 76655',
    role: 'employee',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Software Engineering',
    roomOrUnit: 'Floor 4 - Bay C',
    accessTokenNo: 'INVAR-9901-T',
    accessPin: '9999',
  },
  {
    id: 'worker-amit',
    orgId: 'invartech-solutions',
    name: 'Amit Verma',
    email: 'amit.verma@invartech.com',
    phone: '+91 99550 44332',
    role: 'worker',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    skills: ['IT Support & AV', 'AC & HVAC', 'Network Wiring'],
    rating: 4.85,
    totalJobsCompleted: 165,
    currentWorkload: 1,
    isAvailable: true,
    accessTokenNo: 'INV-WRK-30',
    accessPin: '3030',
  },
  {
    id: 'manager-invar',
    orgId: 'invartech-solutions',
    name: 'Sanjay Kapoor',
    email: 'facilities@invartech.com',
    phone: '+91 99100 88776',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    department: 'Corporate Workplace Services',
    accessTokenNo: 'INV-MGR-40',
    accessPin: '4040',
  },
];

export const DEMO_TICKETS: Ticket[] = [
  // Woxsen University Tickets
  {
    id: 'FOS-2026-004821',
    orgId: 'woxsen-university',
    title: 'Bathroom tap leakage in Room 204',
    description: 'The washbasin tap in the attached bathroom is dripping continuously. Water pressure is wasted and causing sink overflow.',
    serviceId: 'plumbing',
    serviceCategory: 'Plumbing',
    priority: 'high',
    status: 'in_progress',
    location: 'Hostel A',
    building: 'Hostel A',
    block: 'Block B',
    floor: 'Floor 2',
    room: 'Room 204',
    assetId: 'TAP-204-B',
    assetName: 'Washbasin Mixer Tap',
    requesterId: 'user-student-1',
    requesterName: 'Aarav Sharma',
    requesterRole: 'student',
    requesterContact: '+91 98765 43210',
    assignedWorkerId: 'worker-ravi',
    assignedWorkerName: 'Ravi Kumar',
    assignedWorkerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    assignedWorkerSkill: 'Plumbing Technician',
    assignedWorkerPhone: '+91 98220 11223',
    assignedWorkerRating: 4.8,
    managerId: 'manager-warden',
    managerName: 'Dr. Rajesh Verma',
    createdAt: '2026-08-19T09:15:00Z',
    updatedAt: '2026-08-19T11:30:00Z',
    preferredVisitTime: 'Today between 4:00 PM - 6:00 PM',
    deadline: '2026-08-20T09:15:00Z',
    slaHours: 24,
    slaBreached: false,
    escalationLevel: 0,
    attachments: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&auto=format&fit=crop&q=80',
    ],
    workProgress: 50,
    workNotes: 'Replaced tap washer gasket. Currently checking pipe sealing.',
    materialsUsed: ['Standard Brass Washer 1/2"', 'Teflon Sealing Tape'],
    reopenCount: 0,
    timeline: [
      {
        id: 't1',
        timestamp: '2026-08-19 09:15 AM',
        actorName: 'Aarav Sharma',
        actorRole: 'student',
        action: 'Service Request Created',
        notes: 'Raised ticket via Mobile App with attached photo',
      },
      {
        id: 't2',
        timestamp: '2026-08-19 09:30 AM',
        actorName: 'Dr. Rajesh Verma',
        actorRole: 'warden',
        action: 'Under Review',
        notes: 'Verified emergency priority for hostel plumbing',
      },
      {
        id: 't3',
        timestamp: '2026-08-19 10:00 AM',
        actorName: 'Dr. Rajesh Verma',
        actorRole: 'warden',
        action: 'Assigned to Ravi Kumar',
        notes: 'Assigned based on 94% trade match score',
      },
      {
        id: 't4',
        timestamp: '2026-08-19 11:30 AM',
        actorName: 'Ravi Kumar',
        actorRole: 'worker',
        action: 'Work Started (50% complete)',
        notes: 'Dismantled tap casing, replacing internal washer valve',
      },
    ],
    comments: [],
  },
  {
    id: 'FOS-2026-004822',
    orgId: 'woxsen-university',
    title: 'Ceiling fan not working in Room 312',
    description: 'The regulator is loose and fan is making humming noise without spinning. Needs capacitor replacement.',
    serviceId: 'electrical',
    serviceCategory: 'Electrical',
    priority: 'normal',
    status: 'awaiting_verification',
    location: 'Hostel B',
    building: 'Hostel B',
    block: 'Block A',
    floor: 'Floor 3',
    room: 'Room 312',
    assetId: 'FAN-312-A',
    assetName: 'Havells 1200mm Ceiling Fan',
    requesterId: 'user-student-1',
    requesterName: 'Aarav Sharma',
    requesterRole: 'student',
    requesterContact: '+91 97766 55443',
    assignedWorkerId: 'worker-suresh',
    assignedWorkerName: 'Suresh Patel',
    assignedWorkerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    assignedWorkerSkill: 'Electrical Specialist',
    assignedWorkerPhone: '+91 98330 33445',
    assignedWorkerRating: 4.9,
    managerId: 'manager-warden',
    managerName: 'Dr. Rajesh Verma',
    createdAt: '2026-08-18T14:20:00Z',
    updatedAt: '2026-08-19T10:00:00Z',
    deadline: '2026-08-19T14:20:00Z',
    slaHours: 24,
    slaBreached: false,
    escalationLevel: 0,
    attachments: [],
    workProgress: 100,
    workNotes: 'Replaced 2.5mfd capacitor and tested speed regulator. Operating smoothly.',
    workEvidencePhotos: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&auto=format&fit=crop&q=80',
    ],
    materialsUsed: ['Tibcon 2.5uF Motor Capacitor'],
    reopenCount: 0,
    timeline: [
      {
        id: 't21',
        timestamp: '2026-08-18 02:20 PM',
        actorName: 'Aarav Sharma',
        actorRole: 'student',
        action: 'Service Request Created',
      },
      {
        id: 't23',
        timestamp: '2026-08-19 09:30 AM',
        actorName: 'Suresh Patel',
        actorRole: 'worker',
        action: 'Work Completed (100%)',
      },
    ],
    comments: [],
  },

  // Green Valley Residency Tickets
  {
    id: 'FOS-2026-008101',
    orgId: 'green-valley',
    title: 'Elevator Door Sensor Malfunction in Tower 3',
    description: 'Main lobby elevator door sensors fail to detect obstruction automatically. Requires infrared light sensor calibration.',
    serviceId: 'lift_elevator',
    serviceCategory: 'Lift & Elevator',
    priority: 'high',
    status: 'in_progress',
    location: 'Tower 3 Main Lobby',
    building: 'Tower 3',
    floor: 'Ground Floor',
    room: 'Main Lift Well',
    assetId: 'ELEV-T3-GV',
    assetName: 'Schindler 10-Passenger Elevator',
    requesterId: 'user-resident-1',
    requesterName: 'Priya Nambiar',
    requesterRole: 'resident',
    requesterContact: '+91 98111 22334',
    assignedWorkerId: 'worker-karthik',
    assignedWorkerName: 'Karthik Nair',
    assignedWorkerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    assignedWorkerSkill: 'Elevator Maintenance Specialist',
    assignedWorkerPhone: '+91 98770 99881',
    assignedWorkerRating: 4.9,
    managerId: 'manager-green',
    managerName: 'Meera Krishnan',
    createdAt: '2026-08-19T08:00:00Z',
    updatedAt: '2026-08-19T10:30:00Z',
    deadline: '2026-08-19T12:00:00Z',
    slaHours: 4,
    slaBreached: false,
    escalationLevel: 0,
    attachments: [],
    workProgress: 75,
    workNotes: 'Cleaned IR sensor lenses and calibrated safety door curtain beam.',
    reopenCount: 0,
    timeline: [
      {
        id: 'gv1',
        timestamp: '2026-08-19 08:00 AM',
        actorName: 'Priya Nambiar',
        actorRole: 'resident',
        action: 'Service Request Created',
      },
      {
        id: 'gv2',
        timestamp: '2026-08-19 08:30 AM',
        actorName: 'Meera Krishnan',
        actorRole: 'manager',
        action: 'Assigned to Karthik Nair',
      },
    ],
    comments: [],
  },

  // InvarTech Solutions HQ Tickets
  {
    id: 'FOS-2026-009201',
    orgId: 'invartech-solutions',
    title: 'Boardroom AC Chiller Blowing Warm Air',
    description: 'Executive Boardroom HVAC unit compressor tripping every 15 minutes during client meetings.',
    serviceId: 'ac_hvac',
    serviceCategory: 'AC & HVAC',
    priority: 'high',
    status: 'in_progress',
    location: 'HQ Main Block',
    building: 'Main Block',
    floor: 'Floor 5',
    room: 'Executive Boardroom',
    assetId: 'GEN-500-INVAR',
    assetName: 'Central Chiller Unit B',
    requesterId: 'user-employee-1',
    requesterName: 'Vikram Mehta',
    requesterRole: 'employee',
    requesterContact: '+91 99887 76655',
    assignedWorkerId: 'worker-amit',
    assignedWorkerName: 'Amit Verma',
    assignedWorkerAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    assignedWorkerSkill: 'HVAC & IT Technician',
    assignedWorkerPhone: '+91 99550 44332',
    assignedWorkerRating: 4.85,
    managerId: 'manager-invar',
    managerName: 'Sanjay Kapoor',
    createdAt: '2026-08-19T09:00:00Z',
    updatedAt: '2026-08-19T11:00:00Z',
    deadline: '2026-08-19T17:00:00Z',
    slaHours: 8,
    slaBreached: false,
    escalationLevel: 0,
    attachments: [],
    workProgress: 50,
    workNotes: 'Recharged R410A refrigerant gas and cleaned air intake filter.',
    reopenCount: 0,
    timeline: [
      {
        id: 'inv1',
        timestamp: '2026-08-19 09:00 AM',
        actorName: 'Vikram Mehta',
        actorRole: 'employee',
        action: 'Service Request Created',
      },
      {
        id: 'inv2',
        timestamp: '2026-08-19 09:30 AM',
        actorName: 'Sanjay Kapoor',
        actorRole: 'manager',
        action: 'Assigned to Amit Verma',
      },
    ],
    comments: [],
  },
];

export const DEMO_ASSETS: Asset[] = [
  {
    id: 'asset-1',
    assetTag: 'AC-204-B',
    name: 'Daikin 1.5 Ton Split AC',
    category: 'AC & HVAC',
    location: 'Woxsen University',
    building: 'Hostel A',
    room: 'Room 204',
    installationDate: '2024-06-15',
    warrantyUntil: '2027-06-15',
    condition: 'Optimal',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=FACILITYOS-ASSET-AC-204-B',
    lastServiced: '2026-05-10',
    nextScheduledService: '2026-11-10',
  },
];

export const DEMO_SLA_RULES: SLARule[] = [
  {
    id: 'sla-1',
    category: 'Plumbing',
    priority: 'emergency',
    responseTimeHours: 0.5,
    resolutionTimeHours: 2,
  },
];

export const DEMO_PREVENTIVE_SCHEDULES: PreventiveMaintenanceSchedule[] = [
  {
    id: 'pm-1',
    title: 'Monthly Central AC Chiller Inspection',
    assetCategory: 'AC & HVAC',
    facility: 'Academic Block A & B',
    frequency: 'Monthly',
    nextDueDate: '2026-09-01',
    assignedWorkerName: 'Suresh Patel',
    status: 'Scheduled',
    lastCompleted: '2026-08-01',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    title: 'Work Marked Completed',
    message: 'Worker Suresh Patel completed work on FOS-2026-004822. Please verify resolution.',
    timestamp: '10 mins ago',
    read: false,
    type: 'ticket',
    ticketId: 'FOS-2026-004822',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'al-1',
    user: 'Suresh Patel (Worker)',
    action: 'Updated Ticket Progress to 100%',
    ticketId: 'FOS-2026-004822',
    timestamp: '2026-08-19 09:30:15',
    details: 'Status changed from In Progress to Awaiting Verification.',
  },
];
