import {
  Organization,
  ServiceCategory,
  UserProfile,
  Ticket,
  Asset,
  SLARule,
  PreventiveMaintenanceSchedule,
  AuditLogItem,
  AppNotification,
} from './types';

export const GLOBAL_SUPER_ADMIN_ORG: Organization = {
  id: 'global-facilityos-all',
  name: 'FacilityOS Global Platform',
  code: 'FOS-GLOBAL-2026',
  type: 'other',
  location: 'Global Operations Headquarters',
  logo: '🌐',
  primaryColor: '#4f46e5',
  secondaryColor: '#6366f1',
  welcomeMessage: 'FacilityOS System Super Admin Control Hub. Monitoring across all platform tenants.',
  contactEmail: 'superadmin@facilityos.io',
  contactPhone: '+1 800 FACOS SYS',
  verified: true,
  totalServicesCount: 14,
  enabledServiceIds: [
    'plumbing',
    'electrical',
    'carpentry',
    'cleaning',
    'ac_hvac',
    'civil',
    'furniture',
    'wifi_network',
    'it_support',
    'hostel_maint',
    'transport',
    'security_maint',
    'water_supply',
    'lift_elevator',
  ],
};

export const DEMO_ORGANIZATIONS: Organization[] = [
  // WOXSEN UNIVERSITY
  {
    id: 'woxsen-university',
    name: 'Woxsen University',
    code: 'WOXSEN-2026',
    type: 'university',
    location: 'Hyderabad, Telangana',
    logo: '🎓',
    primaryColor: '#1e3a8a',
    secondaryColor: '#3b82f6',
    welcomeMessage: 'Welcome to Woxsen Campus Ops Portal. Report and track facility requests 24/7.',
    contactEmail: 'facility@woxsen.edu.in',
    contactPhone: '+91 40 2345 6789',
    verified: true,
    totalServicesCount: 14,
    enabledServiceIds: [
      'plumbing',
      'electrical',
      'carpentry',
      'cleaning',
      'ac_hvac',
      'civil',
      'furniture',
      'wifi_network',
      'it_support',
      'hostel_maint',
      'transport',
      'security_maint',
      'water_supply',
      'lift_elevator',
    ],
  },
];


export const ALL_SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'plumbing',
    name: 'Plumbing',
    iconName: 'Droplets',
    description: 'Tap leakages, pipe blockages, flush issues, water heaters',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'electrical',
    name: 'Electrical',
    iconName: 'Zap',
    description: 'Lights, switches, power sockets, ceiling fans, MCB trips',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    iconName: 'Hammer',
    description: 'Doors, windows, locks, study tables, wardrobes, cupboards',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 48,
  },
  {
    id: 'cleaning',
    name: 'Cleaning & Housekeeping',
    iconName: 'Droplets',
    description: 'Deep room cleaning, garbage clearance, sanitization',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'ac_hvac',
    name: 'AC & HVAC',
    iconName: 'Wind',
    description: 'AC cooling issues, noise, water leakage from indoor unit, remote control',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'civil',
    name: 'Civil Maintenance',
    iconName: 'Building',
    description: 'Wall dampness, paint peeling, tile damage, roof leakage',
    defaultPriority: 'low',
    enabled: true,
    estimatedHours: 72,
  },
  {
    id: 'furniture',
    name: 'Furniture & Fixtures',
    iconName: 'Armchair',
    description: 'Chair repair, desk adjustments, bed frame, curtains',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 48,
  },
  {
    id: 'wifi_network',
    name: 'Wi-Fi & Network',
    iconName: 'Wifi',
    description: 'LAN port repair, slow internet, router issue, AP offline',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 8,
  },
  {
    id: 'it_support',
    name: 'IT Support & AV',
    iconName: 'Monitor',
    description: 'Projector issues, desktop setup, printer repair, smart board',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'hostel_maint',
    name: 'Hostel Maintenance',
    iconName: 'Bed',
    description: 'Mess equipment, common room TV, laundry machine issue',
    defaultPriority: 'normal',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'transport',
    name: 'Transport & Shuttle',
    iconName: 'Bus',
    description: 'Bus schedule query, EV charger port repair, parking slot',
    defaultPriority: 'low',
    enabled: true,
    estimatedHours: 24,
  },
  {
    id: 'security_maint',
    name: 'Security & Access Control',
    iconName: 'ShieldAlert',
    description: 'Biometric scanner, RFID card key, CCTV camera, gate barrier',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 6,
  },
  {
    id: 'water_supply',
    name: 'Water Supply',
    iconName: 'Waves',
    description: 'Water pressure, main inlet valve, tank overflow',
    defaultPriority: 'high',
    enabled: true,
    estimatedHours: 12,
  },
  {
    id: 'lift_elevator',
    name: 'Lift & Elevator',
    iconName: 'ArrowUpDown',
    description: 'Lift breakdown, door sensor, emergency button check',
    defaultPriority: 'critical',
    enabled: true,
    estimatedHours: 4,
  },
];

export const DEMO_USERS: UserProfile[] = [
  // Woxsen University Users
  {
    id: 'user-student-1',
    orgId: 'woxsen-university',
    name: 'Aarav Sharma',
    email: 'student@woxsen.edu.in',
    phone: '+91 98765 43210',
    role: 'student',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Computer Science (B.Tech 3rd Yr)',
    roomOrUnit: 'Hostel B - Room 204',
    rollNo: 'WOX-2026-84920',
    admissionNo: '58492',
    courseSection: 'B.Tech CSE - Sec A',
    approvalStatus: 'ACTIVE',
    accessTokenNo: 'WOX-8849-T',
    accessPin: '2026',
  },
  {
    id: 'worker-ravi',
    orgId: 'woxsen-university',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@woxsen.edu.in',
    phone: '+91 98220 11223',
    role: 'worker',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    skills: ['Plumbing', 'Water Supply', 'Sanitary Fittings'],
    rating: 4.8,
    totalJobsCompleted: 142,
    currentWorkload: 1,
    isAvailable: true,
    accessTokenNo: 'WRK-5050-T',
    accessPin: '5050',
  },
  {
    id: 'worker-suresh',
    orgId: 'woxsen-university',
    name: 'Suresh Patel',
    email: 'suresh.patel@woxsen.edu.in',
    phone: '+91 98330 33445',
    role: 'worker',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    skills: ['Electrical', 'AC & HVAC', 'Fan Repair'],
    rating: 4.9,
    totalJobsCompleted: 198,
    currentWorkload: 2,
    isAvailable: true,
    accessTokenNo: 'WRK-6060-T',
    accessPin: '6060',
  },
  {
    id: 'manager-warden',
    orgId: 'woxsen-university',
    name: 'Dr. Rajesh Verma',
    email: 'warden.hostela@woxsen.edu.in',
    phone: '+91 94450 99887',
    role: 'warden',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    department: 'Assigned: Block A, Block B, Tower T1, Tower T2, Tower T5, Tower T6',
    assignedBlocks: ['Block A', 'Block B', 'Tower T1', 'Tower T2', 'Tower T5', 'Tower T6'],
    accessTokenNo: 'WDN-3030-T',
    accessPin: '3030',
  },
  {
    id: 'courier-manager-1',
    orgId: 'woxsen-university',
    name: 'Courier Desk Manager',
    email: 'courier.manager@woxsen.edu.in',
    phone: '+91 98888 11111',
    role: 'courier_manager',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    department: 'Mailroom & Logistics Operations',
    accessTokenNo: 'CLM-1010-T',
    accessPin: '1010',
  },
  {
    id: 'sports-manager-1',
    orgId: 'woxsen-university',
    name: 'Sports Area Manager',
    email: 'sports.manager@woxsen.edu.in',
    phone: '+91 98888 22222',
    role: 'sports_manager',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    department: 'Sports Arena & Recreation Complex',
    accessTokenNo: 'SPM-2020-T',
    accessPin: '2020',
  },
  {
    id: 'laundry-manager-1',
    orgId: 'woxsen-university',
    name: 'Laundry Operations Manager',
    email: 'laundry.manager@woxsen.edu.in',
    phone: '+91 98888 33333',
    role: 'laundry_manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Hostel Washer Bays & Laundry Operations',
    accessTokenNo: 'LND-4040-T',
    accessPin: '4040',
  },
  {
    id: 'vendor-asianwok',
    orgId: 'woxsen-university',
    name: 'Asian Wok & Rice Bowl Manager',
    email: 'vendor.asianwok@woxsen.edu.in',
    phone: '+91 98888 44001',
    role: 'food_manager',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    department: 'Woxsen Asian Wok Outlet (Chinese & Starters)',
    accessTokenNo: 'WOK-1010-T',
    accessPin: '1010',
  },
  {
    id: 'vendor-burgerdeck',
    orgId: 'woxsen-university',
    name: 'Crust & Burger Deck Manager',
    email: 'vendor.burgerdeck@woxsen.edu.in',
    phone: '+91 98888 44002',
    role: 'food_manager',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    department: 'Wood-Fired Crust & Burger Deck (Pizzas & Desserts)',
    accessTokenNo: 'BGR-2020-T',
    accessPin: '2020',
  },
  {
    id: 'vendor-crispycrunch',
    orgId: 'woxsen-university',
    name: 'Crispy Crunch KFC-Style Manager',
    email: 'vendor.crispycrunch@woxsen.edu.in',
    phone: '+91 98888 44003',
    role: 'food_manager',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    department: 'Woxsen Crispy Crunch (Buckets & Nuggets)',
    accessTokenNo: 'KFC-3030-T',
    accessPin: '3030',
  },
  {
    id: 'vendor-expressbites',
    orgId: 'woxsen-university',
    name: 'Express Bites & Chai Manager',
    email: 'vendor.expressbites@woxsen.edu.in',
    phone: '+91 98888 44004',
    role: 'food_manager',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Woxsen Express Bites (Samosas, Puffs, Chai)',
    accessTokenNo: 'EXP-4040-T',
    accessPin: '4040',
  },
  {
    id: 'admin-1',
    orgId: 'woxsen-university',
    name: 'Ananya Reddy',
    email: 'admin@woxsen.edu.in',
    phone: '+91 90000 12345',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Chief Facility Officer',
    accessTokenNo: 'ADM-1010-T',
    accessPin: '1010',
  },
];

export const DEMO_TICKETS: Ticket[] = [
  // Woxsen University Tickets
  {
    id: 'FOS-2026-004821',
    orgId: 'woxsen-university',
    title: 'Bathroom tap leakage in Room 204',
    description: 'The washbasin tap in the attached bathroom is dripping continuously. Water pressure is wasted and causing sink overflow.',
    serviceId: 'plumbing',
    serviceCategory: 'Plumbing',
    priority: 'high',
    status: 'in_progress',
    location: 'Hostel A',
    building: 'Hostel A',
    block: 'Block B',
    floor: 'Floor 2',
    room: 'Room 204',
    assetId: 'TAP-204-B',
    assetName: 'Washbasin Mixer Tap',
    requesterId: 'user-student-1',
    requesterName: 'Aarav Sharma',
    requesterRole: 'student',
    requesterContact: '+91 98765 43210',
    assignedWorkerId: 'worker-ravi',
    assignedWorkerName: 'Ravi Kumar',
    assignedWorkerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    assignedWorkerSkill: 'Plumbing Technician',
    assignedWorkerPhone: '+91 98220 11223',
    assignedWorkerRating: 4.8,
    managerId: 'manager-warden',
    managerName: 'Dr. Rajesh Verma',
    createdAt: '2026-08-19T09:15:00Z',
    updatedAt: '2026-08-19T11:30:00Z',
    preferredVisitTime: 'Today between 4:00 PM - 6:00 PM',
    deadline: '2026-08-20T09:15:00Z',
    slaHours: 24,
    slaBreached: false,
    escalationLevel: 0,
    attachments: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&auto=format&fit=crop&q=80',
    ],
    workProgress: 50,
    workNotes: 'Replaced tap washer gasket. Currently checking pipe sealing.',
    materialsUsed: ['Standard Brass Washer 1/2"', 'Teflon Sealing Tape'],
    reopenCount: 0,
    timeline: [
      {
        id: 't1',
        timestamp: '2026-08-19 09:15 AM',
        actorName: 'Aarav Sharma',
        actorRole: 'student',
        action: 'Service Request Created',
        notes: 'Raised ticket via Mobile App with attached photo',
      },
      {
        id: 't2',
        timestamp: '2026-08-19 09:30 AM',
        actorName: 'Dr. Rajesh Verma',
        actorRole: 'warden',
        action: 'Under Review',
        notes: 'Verified emergency priority for hostel plumbing',
      },
      {
        id: 't3',
        timestamp: '2026-08-19 10:00 AM',
        actorName: 'Dr. Rajesh Verma',
        actorRole: 'warden',
        action: 'Assigned to Ravi Kumar',
        notes: 'Assigned based on 94% trade match score',
      },
      {
        id: 't4',
        timestamp: '2026-08-19 11:30 AM',
        actorName: 'Ravi Kumar',
        actorRole: 'worker',
        action: 'Work Started (50% complete)',
        notes: 'Dismantled tap casing, replacing internal washer valve',
      },
    ],
    comments: [],
  },
  {
    id: 'FOS-2026-004822',
    orgId: 'woxsen-university',
    title: 'Ceiling fan not working in Room 312',
    description: 'The regulator is loose and fan is making humming noise without spinning. Needs capacitor replacement.',
    serviceId: 'electrical',
    serviceCategory: 'Electrical',
    priority: 'normal',
    status: 'awaiting_verification',
    location: 'Hostel B',
    building: 'Hostel B',
    block: 'Block A',
    floor: 'Floor 3',
    room: 'Room 312',
    assetId: 'FAN-312-A',
    assetName: 'Havells 1200mm Ceiling Fan',
    requesterId: 'user-student-1',
    requesterName: 'Aarav Sharma',
    requesterRole: 'student',
    requesterContact: '+91 97766 55443',
    assignedWorkerId: 'worker-suresh',
    assignedWorkerName: 'Suresh Patel',
    assignedWorkerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    assignedWorkerSkill: 'Electrical Specialist',
    assignedWorkerPhone: '+91 98330 33445',
    assignedWorkerRating: 4.9,
    managerId: 'manager-warden',
    managerName: 'Dr. Rajesh Verma',
    createdAt: '2026-08-18T14:20:00Z',
    updatedAt: '2026-08-19T10:00:00Z',
    deadline: '2026-08-19T14:20:00Z',
    slaHours: 24,
    slaBreached: false,
    escalationLevel: 0,
    attachments: [],
    workProgress: 100,
    workNotes: 'Replaced 2.5mfd capacitor and tested speed regulator. Operating smoothly.',
    workEvidencePhotos: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&auto=format&fit=crop&q=80',
    ],
    materialsUsed: ['Tibcon 2.5uF Motor Capacitor'],
    reopenCount: 0,
    timeline: [
      {
        id: 't21',
        timestamp: '2026-08-18 02:20 PM',
        actorName: 'Aarav Sharma',
        actorRole: 'student',
        action: 'Service Request Created',
      },
      {
        id: 't23',
        timestamp: '2026-08-19 09:30 AM',
        actorName: 'Suresh Patel',
        actorRole: 'worker',
        action: 'Work Completed (100%)',
      },
    ],
    comments: [],
  },
];

export const DEMO_ASSETS: Asset[] = [
  {
    id: 'asset-1',
    assetTag: 'AC-204-B',
    name: 'Daikin 1.5 Ton Split AC',
    category: 'AC & HVAC',
    location: 'Woxsen University',
    building: 'Hostel A',
    room: 'Room 204',
    installationDate: '2024-06-15',
    warrantyUntil: '2027-06-15',
    condition: 'Optimal',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=FACILITYOS-ASSET-AC-204-B',
    lastServiced: '2026-05-10',
    nextScheduledService: '2026-11-10',
  },
];

export const DEMO_SLA_RULES: SLARule[] = [
  {
    id: 'sla-1',
    category: 'Plumbing',
    priority: 'emergency',
    responseTimeHours: 0.5,
    resolutionTimeHours: 2,
  },
  {
    id: 'sla-2',
    category: 'Electrical',
    priority: 'high',
    responseTimeHours: 1,
    resolutionTimeHours: 4,
  },
  {
    id: 'sla-3',
    category: 'AC & HVAC',
    priority: 'high',
    responseTimeHours: 2,
    resolutionTimeHours: 6,
  },
  {
    id: 'sla-4',
    category: 'Networking & Wifi',
    priority: 'normal',
    responseTimeHours: 2,
    resolutionTimeHours: 12,
  },
  {
    id: 'sla-5',
    category: 'Carpentry & Locksmith',
    priority: 'normal',
    responseTimeHours: 4,
    resolutionTimeHours: 24,
  },
];

export const DEMO_PREVENTIVE_SCHEDULES: PreventiveMaintenanceSchedule[] = [
  {
    id: 'pm-1',
    title: 'Monthly Central AC Chiller Inspection',
    assetCategory: 'AC & HVAC',
    facility: 'Academic Block A & B',
    frequency: 'Monthly',
    nextDueDate: '2026-09-01',
    assignedWorkerName: 'Suresh Patel',
    status: 'Scheduled',
    lastCompleted: '2026-08-01',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    title: 'Work Marked Completed',
    message: 'Worker Suresh Patel completed work on FOS-2026-004822. Please verify resolution.',
    timestamp: '10 mins ago',
    read: false,
    type: 'ticket',
    ticketId: 'FOS-2026-004822',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'al-1',
    user: 'Aarav Sharma',
    action: 'Ticket Created',
    ticketId: 'FOS-2026-004821',
    timestamp: '2 hours ago',
    details: 'Submitted Plumbing & Sanitary request for Room 204.',
  },
];

export const INITIAL_ROOM_CHANGE_REQUESTS: any[] = [
  {
    id: 'RCR-8401',
    studentId: 'user-student-2',
    studentName: 'S. Bharat Reddy',
    studentEmail: 'bharat.reddy@woxsen.edu.in',
    currentRoom: 'Hostel Block A - Room 102',
    requestedTower: 'Tower T1',
    requestedFloor: 5,
    requestedRoom: 'Tower T1 - Room 502',
    reason: 'Medical condition requiring elevator access and air conditioning.',
    status: 'PENDING_WARDEN_APPROVAL',
    createdAt: '2026-09-02T14:30:00.000Z',
  },
];

export const INITIAL_ROOM_TRANSFER_HISTORY: any[] = [
  {
    id: 'RTH-901',
    studentId: 'user-student-1',
    studentName: 'Aarav Sharma',
    previousRoom: 'Hostel Block A - Room 101',
    newRoom: 'Hostel B - Room 204',
    reason: 'Warden Room Allocation Optimization',
    approvedBy: 'Dr. Rajesh Verma (Warden)',
    timestamp: '2026-08-15T10:00:00.000Z',
  },
];

export const INITIAL_MASTER_INCIDENTS: any[] = [
  {
    id: 'INC-2026-041',
    title: 'Floor 3 Central AC Cooling Failure',
    category: 'AC & HVAC',
    building: 'Tower T1',
    floor: 'Floor 3',
    affectedRooms: ['Tower T1 - Room 301', 'Tower T1 - Room 302', 'Tower T1 - Room 303'],
    complaintCount: 3,
    status: 'active',
    possibleRootCause: 'Chilled water supply valve blockage on Floor 3 riser.',
    recommendedAction: 'Inspect Floor 3 HVAC riser valve and clear strainer.',
  },
];

export const INITIAL_SECTORS = [
  { id: 't1', name: 'Tower T1', type: 'tower' as const, capacity: '12 Floors • 24 Rooms/Floor • 3 Members/Room (864 Student Capacity | Rooms T1-001 to T1-1224)', roomsCount: 288, floorsCount: 12, roomsPerFloor: 24, occupantsPerRoom: 3, roomFormat: 'T1-001 to T1-1224', assignedWarden: 'Dr. Rajesh Verma' },
  { id: 't2', name: 'Tower T2', type: 'tower' as const, capacity: '14 Floors • 24 Rooms/Floor • 3 Members/Room (1,008 Student Capacity | Rooms T2-001 to T2-1424)', roomsCount: 336, floorsCount: 14, roomsPerFloor: 24, occupantsPerRoom: 3, roomFormat: 'T2-001 to T2-1424', assignedWarden: 'Dr. Rajesh Verma' },
  { id: 't3', name: 'Tower T3', type: 'tower' as const, capacity: '14 Floors • 24 Rooms/Floor • 3 Members/Room (1,008 Student Capacity | Rooms T3-001 to T3-1424)', roomsCount: 336, floorsCount: 14, roomsPerFloor: 24, occupantsPerRoom: 3, roomFormat: 'T3-001 to T3-1424', assignedWarden: 'Unassigned' },
  { id: 't4', name: 'Tower T4', type: 'tower' as const, capacity: '14 Floors • 24 Rooms/Floor • 3 Members/Room (1,008 Student Capacity | Rooms T4-001 to T4-1424)', roomsCount: 336, floorsCount: 14, roomsPerFloor: 24, occupantsPerRoom: 3, roomFormat: 'T4-001 to T4-1424', assignedWarden: 'Dr. Ananya Sharma' },
  { id: 't5', name: 'Tower T5', type: 'tower' as const, capacity: '14 Floors • 24 Rooms/Floor • 3 Members/Room (1,008 Student Capacity | Rooms T5-001 to T5-1424)', roomsCount: 336, floorsCount: 14, roomsPerFloor: 24, occupantsPerRoom: 3, roomFormat: 'T5-001 to T5-1424', assignedWarden: 'Dr. Rajesh Verma' },
  { id: 't6', name: 'Tower T6', type: 'tower' as const, capacity: '14 Floors • 24 Rooms/Floor • 3 Members/Room (1,008 Student Capacity | Rooms T6-001 to T6-1424)', roomsCount: 336, floorsCount: 14, roomsPerFloor: 24, occupantsPerRoom: 3, roomFormat: 'T6-001 to T6-1424', assignedWarden: 'Dr. Rajesh Verma' },
  { id: 't7', name: 'Tower T7', type: 'tower' as const, capacity: '14 Floors • 24 Rooms/Floor • 3 Members/Room (1,008 Student Capacity | Rooms T7-001 to T7-1424)', roomsCount: 336, floorsCount: 14, roomsPerFloor: 24, occupantsPerRoom: 3, roomFormat: 'T7-001 to T7-1424', assignedWarden: 'Unassigned' },
  { id: 'blk-a', name: 'Block A', type: 'block' as const, capacity: '5 Floors • 20 Rooms/Floor • 3 Members/Room (300 Student Capacity | Rooms A-001 to A-520)', roomsCount: 100, floorsCount: 5, roomsPerFloor: 20, occupantsPerRoom: 3, roomFormat: 'A-001 to A-520', assignedWarden: 'Dr. Rajesh Verma' },
  { id: 'blk-b', name: 'Block B', type: 'block' as const, capacity: '5 Floors • 20 Rooms/Floor • 3 Members/Room (300 Student Capacity | Rooms B-001 to B-520)', roomsCount: 100, floorsCount: 5, roomsPerFloor: 20, occupantsPerRoom: 3, roomFormat: 'B-001 to B-520', assignedWarden: 'Dr. Rajesh Verma' },
  { id: 'blk-c', name: 'Block C', type: 'block' as const, capacity: '5 Floors • 20 Rooms/Floor • 3 Members/Room (300 Student Capacity | Rooms C-001 to C-520)', roomsCount: 100, floorsCount: 5, roomsPerFloor: 20, occupantsPerRoom: 3, roomFormat: 'C-001 to C-520', assignedWarden: 'Unassigned' },
  { id: 'blk-d', name: 'Block D', type: 'block' as const, capacity: '5 Floors • 20 Rooms/Floor • 3 Members/Room (300 Student Capacity | Rooms D-001 to D-520)', roomsCount: 100, floorsCount: 5, roomsPerFloor: 20, occupantsPerRoom: 3, roomFormat: 'D-001 to D-520', assignedWarden: 'Unassigned' },
  { id: 'blk-e', name: 'Block E', type: 'block' as const, capacity: '5 Floors • 20 Rooms/Floor • 3 Members/Room (300 Student Capacity | Rooms E-001 to E-520)', roomsCount: 100, floorsCount: 5, roomsPerFloor: 20, occupantsPerRoom: 3, roomFormat: 'E-001 to E-520', assignedWarden: 'Unassigned' },
  { id: 'blk-f', name: 'Block F', type: 'block' as const, capacity: '5 Floors • 20 Rooms/Floor • 3 Members/Room (300 Student Capacity | Rooms F-001 to F-520)', roomsCount: 100, floorsCount: 5, roomsPerFloor: 20, occupantsPerRoom: 3, roomFormat: 'F-001 to F-520', assignedWarden: 'Unassigned' },
  { id: 'blk-g', name: 'Block G', type: 'block' as const, capacity: '5 Floors • 20 Rooms/Floor • 3 Members/Room (300 Student Capacity | Rooms G-001 to G-520)', roomsCount: 100, floorsCount: 5, roomsPerFloor: 20, occupantsPerRoom: 3, roomFormat: 'G-001 to G-520', assignedWarden: 'Unassigned' },
];
